name:                elm-ethereum-generator
version:             4.0.0
github:              "cmditch/elm-ethereum-generator"
license:             BSD3
author:              "Coury Ditch"
maintainer:          "os@cmdit.ch"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/cmditch/elm-ethereum-generator#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- directory
- filepath
- pretty
- optparse-applicative
- ansi-wl-pprint
- process
- text
- ilist
- parsec
- cryptonite

library:
  source-dirs: src

executables:
  elm-ethereum-generator-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-ethereum-generator

tests:
  elm-ethereum-generator-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elm-ethereum-generator
