module Contracts.ERC20 exposing
    ( Approval
    , Transfer
    , allowance
    , allowed
    , approvalDecoder
    , approvalEvent
    , approve
    , balanceOf
    , balances
    , decimals
    , name
    , symbol
    , totalSupply
    , transfer
    , transferDecoder
    , transferEvent
    , transferFrom
    )

import Abi.Decode as AbiDecode exposing (abiDecode, andMap, data, toElmDecoder, topic)
import Abi.Encode as AbiEncode exposing (Encoding(..), abiEncode)
import BigInt exposing (BigInt)
import Eth.Types exposing (..)
import Eth.Utils as U
import Json.Decode as Decode exposing (Decoder)
import Json.Decode.Pipeline exposing (custom, decode)



{-

   This file was generated by https://github.com/cmditch/elm-ethereum-generator

-}


{-| "allowance(address,address)" function
-}
allowance : Address -> Address -> Address -> Call BigInt
allowance contractAddress owner spender =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "allowance(address,address)" [ AbiEncode.address owner, AbiEncode.address spender ]
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.uint
    }


{-| "allowed(address,address)" function
-}
allowed : Address -> Address -> Address -> Call BigInt
allowed contractAddress a b =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "allowed(address,address)" [ AbiEncode.address a, AbiEncode.address b ]
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.uint
    }


{-| "approve(address,uint256)" function
-}
approve : Address -> Address -> BigInt -> Call Bool
approve contractAddress spender value =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "approve(address,uint256)" [ AbiEncode.address spender, AbiEncode.uint value ]
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.bool
    }


{-| "balanceOf(address)" function
-}
balanceOf : Address -> Address -> Call BigInt
balanceOf contractAddress owner =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "balanceOf(address)" [ AbiEncode.address owner ]
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.uint
    }


{-| "balances(address)" function
-}
balances : Address -> Address -> Call BigInt
balances contractAddress a =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "balances(address)" [ AbiEncode.address a ]
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.uint
    }


{-| "decimals()" function
-}
decimals : Address -> Call BigInt
decimals contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "decimals()" []
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.uint
    }


{-| "name()" function
-}
name : Address -> Call String
name contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "name()" []
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.string
    }


{-| "symbol()" function
-}
symbol : Address -> Call String
symbol contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "symbol()" []
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.string
    }


{-| "totalSupply()" function
-}
totalSupply : Address -> Call BigInt
totalSupply contractAddress =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "totalSupply()" []
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.uint
    }


{-| "transfer(address,uint256)" function
-}
transfer : Address -> Address -> BigInt -> Call Bool
transfer contractAddress to value =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "transfer(address,uint256)" [ AbiEncode.address to, AbiEncode.uint value ]
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.bool
    }


{-| "transferFrom(address,address,uint256)" function
-}
transferFrom : Address -> Address -> Address -> BigInt -> Call Bool
transferFrom contractAddress from to value =
    { to = Just contractAddress
    , from = Nothing
    , gas = Nothing
    , gasPrice = Nothing
    , value = Nothing
    , data = Just <| AbiEncode.functionCall "transferFrom(address,address,uint256)" [ AbiEncode.address from, AbiEncode.address to, AbiEncode.uint value ]
    , nonce = Nothing
    , decoder = toElmDecoder AbiDecode.bool
    }


{-| "Approval(address,address,uint256)" event
-}
type alias Approval =
    { owner : Address
    , spender : Address
    , value : BigInt
    }


approvalEvent : Address -> Maybe Address -> Maybe Address -> LogFilter
approvalEvent contractAddress owner spender =
    { fromBlock = LatestBlock
    , toBlock = LatestBlock
    , address = contractAddress
    , topics =
        [ Just <| U.keccak256 "Approval(address,address,uint256)"
        , Maybe.map (abiEncode << AbiEncode.address) owner
        , Maybe.map (abiEncode << AbiEncode.address) spender
        ]
    }


approvalDecoder : Decoder Approval
approvalDecoder =
    decode Approval
        |> custom (topic 1 AbiDecode.address)
        |> custom (topic 2 AbiDecode.address)
        |> custom (data 0 AbiDecode.uint)


{-| "Transfer(address,address,uint256)" event
-}
type alias Transfer =
    { from : Address
    , to : Address
    , value : BigInt
    }


transferEvent : Address -> Maybe Address -> Maybe Address -> LogFilter
transferEvent contractAddress from to =
    { fromBlock = LatestBlock
    , toBlock = LatestBlock
    , address = contractAddress
    , topics =
        [ Just <| U.keccak256 "Transfer(address,address,uint256)"
        , Maybe.map (abiEncode << AbiEncode.address) from
        , Maybe.map (abiEncode << AbiEncode.address) to
        ]
    }


transferDecoder : Decoder Transfer
transferDecoder =
    decode Transfer
        |> custom (topic 1 AbiDecode.address)
        |> custom (topic 2 AbiDecode.address)
        |> custom (data 0 AbiDecode.uint)
